---
title: "Principios (y fundamentos) del proceso laboral"
subtitle: ""
author: "Paul Paredes"
institute: "Maestría en Derecho Procesal, UNMSM"
date: "26 de junio de 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css:
      - default
      - default-fonts 
      - "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css"
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    self_contained: true
---

class: center, middle, animated, slideInRight

# La clase anterior

---
class: animated, fadeIn

### - ¿Por qué plantear una reforma de la justicia laboral?

### - Los ejes (oficiales) de la reforma procesal

  1. La oralidad

  2. Uso intensivo de la tecnología

  3. El acceso a la justicia

### - Qué actividades se realizaron para elaborar el nuevo diseño procesal

### - Tareas de la reforma

  1. Formación y capacitación

  2. Implementación material de los despachos. Infraestructura

  3. La NLPT

  4. Seguimiento y retroalimentación del nuevo proceso
  
---
class: animated, fadeIn

### - Beneficios de la reforma

  1. Celeridad: 6 meses

  2. Ensanchamiento de la base poblacional con acceso a la justicia laboral

  3. Simplicidad del procedimiento

  4. Predictibilidad de la justicia laboral

  5. Modernidad de los procedimientos

  6. Revaloración del rol de la Corte Suprema

---
class: animated, fadeIn

### -La oralidad

  - ¿La Ley 26636 regula, incorpora, describe un proceso *escrito*?

### - Uso intensivo de la tecnología

  1. Notificaciones electrónicas, a cargo del PJ

  2. Expediente electrónico, a cargo del PJ

  3. Base de datos de jurisprudencia y precedentes sistematizada, a cargo del MTPE, con la colaboración del PJ y TC

  4. Sistema de cálculo de derechos laborales, a cargo del MTPE con la colaboración del PJ

  5. Sistema de remisión electrónico de información de las planillas electrónicas, a cargo del MTPE

---
class: animated, fadeIn

### La reforma en América Latina

### Países que han implementado reformas laborales

+ Venezuela, agosto 2003

+ Ecuador, julio 2004

+ Colombia, enero 2008

+ Chile, marzo 2008

+ Bolivia, (1979), 2009

+ Uruguay, febrero 2010

+ Perú, enero-julio 2010

---
class: animated, fadeIn

### La experiencia ecuatoriana 

### La experiencia venezolana

### La tendencia actual a la oralidad

+ Mayor dosis de oralidad (que no excluye la escritura, sino que acerca, concentra y simplifica)

+ Uso de nuevas tecnologías

+ Rol protagónico del juez

+ Fortalecimiento de los mecanismos alternativos de solución de conflictos

+ Protección especial frente a la vulneración de derechos fundamentales

---
class: center, middle, animated, slideInRight

# Clase 2

# Principios (y fundamentos) del proceso laboral

---
class: inverse, center, middle, animated, bounceInDown

# ¡Empecemos!

---
class: animated, slideInRight, center, middle

# ¿Por qué (debe haber) un proceso laboral?

---
class: animated, fadeIn

# Poder. Estado social. 
  + Intervención en la economía para asegurar ciertos derechos básicos

# Justicia
  + Justicia distributiva
  + Justicia correctiva (conmutativa)

---
class: animated, fadeIn

# Igualdad (en la distribución)
  + De características
  + De trato (a los iguales, misma categoría)
    + a c/u lo mismo
    + a c/u lo de la ley
    + a c/u según su rango
    + a c/u según su mérito
    + a c/u según su trabajo
    + a c/u según su necesidad

# Igualdad (¿cómo distribuir?)
  + En el proceso de distribución igualitario
  + En el resultado igualitario
  
---
class: animated, fadeIn  

# Tres nociones de igualdad en las constituciones

1. Igualdad política
  + Reparto del poder político en una sociedad
  + Participación en la producción de las normas jurídicas

2. Igualdad ante la ley
  + Normas generales y no arbitrarias: casos iguales, se resuelven iguales
  + Prohibición de discriminar: (no siempre hay que tratar igual a todos en ciertas circunstancias, pero nunca se puede utilizar ciertas características para diferenciar el trato)

3. Igualdad en la ley (a través de la ley)
  + La aplicación del Derecho debe producir resultados igualitarios en cuanto a las condiciones de vida de los ciudadanos
  + Podría parecer ir contra la igualdad ante la ley en abstracto (acción afirmativa)

---
class: animated, fadeIn

# Couture

### **Couture** planteó que la razón de ser del Derecho procesal del trabajo era asegurar ciertos resultados mínimos de justicia dentro de la desigual relación del trabajo, y que para lograrlo era necesario establecer la igualdad mediante una desigualdad: la igualdad por compensación.

.left-column[
# Pregunta:
]
.right-column[
### ¿Qué noción de igualdad daría respaldo a su postura?
]

---
class: animated, fadeIn

# Impacto de la desigualdad (económica y social)

+ En la configuración de las relaciones laborales

+ En el valor epistémico de la prueba

+ En valores de política pública (p. ej. la justicia distributiva)

---
class: animated, fadeIn

# La desigualdad como fundamento del proceso laboral (dos perspectivas)

## 1. La desigualdad material y la igualdad por compensación

## 2. La igualdad en el principio dispositivo

---
class: animated, fadeIn

# 1. La desigualdad material y la igualdad por compensación

1. La igualdad por compensación: el procedimiento lógico de corregir las desigualdades es el crear otras desigualdades
  + El principio de imparcialidad: igualdad de armas
    + Quien produce y conserva un medio de prueba | Sin acceso al medio de prueba
    + Quien dispone cómo ejecutar un servicio y cómo se deja constancia de ello | Quien está sometido a las órdenes
    + La igualdad de armas es un objetivo por cumplir
    + Importancia de los poderes del juez

**+ La igualdad por compensación se posiciona como el fundamento de las actuaciones procesales en los conflictos laborales**.

---
class: animated, fadeIn

# Tres datos como respaldo epistémico a la desigualdads de las relaciones jurídicas laborales en el Perú

## 1. Informalidad laboral: en 2015, 55.5%; en microempresas, 88.7%

## 2. Contratos a plazo fijo: 78% fijos vs. 22% indeterminado

## 3. Sindicación y cobertura de la negociación colectiva: 6% y 5.1%, respectivamente.

---
class: animated, fadeIn

# 2. La igualdad en el principio dispositivo

1. El principio dispositivo (según lo alegado y probado) prohíbe apreciar, de oficio, hechos relevantes que constan en el proceso pero que no han sido propuestos expresamente por las partes.

2. De vincular al juez a lo alegado y probado no se sigue, necesariamente, que la actuación del juez esté completamente sometida a las partes.

---
class: animated, fadeIn

# Principio dispositivo

+ Afirmar la sujeción del juez a la soberanía de las partes camufla una idea de desigualdad: si las partes son soberanas, entonces, son igualmente soberanas.

+ ¿Son las partes iguales?

+ Si todo se deja al principio dispositivo (en su versión más restrictiva), entonces se niega el derecho de defensa de una de las partes.

+ Se trata de afirmar el p. dispositivo pero sin llevar a convertir al proceso en "una cosa de las partes"

+ Presencia de algunas notas del p. inquisitivo en clave de optimización de la decisión. 

+ Pero también en clave de optimización epistémica (evitar que se cree una realidad paralela y el sistema procesal no tendría nada que decir)

---
class: animated, fadeIn

### Mario Pasco. Fundamentos de derecho procesal del trabajo

### Principios del derecho procesal del trabajo 

### A. VERACIDAD 
1. Limitación al formalismo (prevalencia fondo sobre forma)
  + simplicidad 
  + prohibición de pruebas (juramento decisorio)
  + relativización de ciertas pruebas (declaración de parte, confesión, instrumentos)
  + libertad probatoria 

2. Ampliación facultades juez
  + inhibición de oficio 
  + suplencia demanda 
  + impulso procesal 
  + sentencia inmediata 

3. Facultad ultra y extra petita 

---
class: animated, fadeIn

### B. PRINCIPIO PROTECTOR 
1. Reglas pro operario 
  + Retroactividad 
  + In dubio pro operario 
  + Norma más favorable 
  + Condición más beneficiosa 

2. Iniciativa de oficio del proceso 

3. Redistribución de la carga de la prueba 

4. Otras normas de protección 
  + Gratuidad 
  + Defensa gratuita 
  + Oralidad, concentración, inmediación, celebridad 

5. Ponderación ecuánime del principio protector 

---
class: animated, fadeIn

### C. CRITERIO DE CONCIENCIA Y EQUIDAD 
1. Criterio de conciencia en la evaluación de las pruebas 
2. Equidad 

### Tres funciones de los principios 
1. Informadora. Inspira al legislador. 
2. Normativa. Fuente supletoria. 
3. Interpretadora. 

---
class: animated, fadeIn

# NLPT

> Artículo I.- Principios del proceso laboral

> El proceso laboral se inspira, entre otros, en los principios de inmediación, oralidad, concentración, celeridad, economía procesal y veracidad.
	
---
class: animated, fadeIn

# NLPT

> Artículo II.- Ámbito de la justicia laboral
> Corresponde a la justicia laboral resolver los conflictos jurídicos que se originan con ocasión de las prestaciones de servicios de carácter personal, de naturaleza laboral, formativa, cooperativista o administrativa; están excluidas las prestaciones de servicios de carácter civil, salvo que la demanda se sustente en el encubrimiento de relaciones de trabajo. Tales conflictos jurídicos pueden ser individuales, plurales o colectivos, y estar referidos a aspectos sustanciales o conexos, incluso previos o posteriores a la prestación efectiva de los servicios.

---
class: animated, fadeIn

# NLPT 

>Artículo III.- Fundamentos del proceso laboral

>En todo proceso laboral los jueces deben evitar que la desigualdad entre las partes afecte el desarrollo o resultado del proceso, para cuyo efecto procuran alcanzar la igualdad real de las partes, privilegian el fondo sobre la forma, interpretan los requisitos y presupuestos procesales en sentido favorable a la continuidad del proceso, observan el debido proceso, la tutela jurisdiccional y el principio de razonabilidad. En particular, acentúan estos deberes frente a la madre gestante, el menor de edad y la persona con discapacidad.

> Los jueces laborales tienen un rol protagónico en el desarrollo e impulso del proceso. Impiden y sancionan la inconducta contraria a los deberes de veracidad, probidad, lealtad y buena fe de las partes, sus representantes, sus abogados y terceros.

> El proceso laboral es gratuito para el prestador de servicios, en todas las instancias, cuando el monto total de las pretensiones reclamadas no supere las setenta (70) Unidades de Referencia Procesal (URP).

---
class: animated, fadeIn

# NLPT

> Artículo IV.- Interpretación y aplicación de las normas en la resolución de los conflictos de la justicia laboral

> Los jueces laborales, bajo responsabilidad, imparten justicia con arreglo a la Constitución Política del Perú, los tratados internacionales de derechos humanos y la ley. Interpretan y aplican toda norma jurídica, incluyendo los convenios colectivos, según los principios y preceptos constitucionales, así como los precedentes vinculantes del Tribunal Constitucional y de la Corte Suprema de Justicia de la República.

---
class: animated, fadeIn

# En otros países

+ Oralidad
+ Gratuidad
+ Prueba de oficio
+ Ultra petita (Colombia, Chile, Venezuela)
+ Extra petita (Colombia, Venezuela)

---
class: inverse, center, middle, animated, bounceInDown
# ¡Gracias!