#!/bin/bash -e

cd "$( dirname "${BASH_SOURCE[0]}" )/.."

export JAVA_HOME=$(/usr/libexec/java_home -v 11+)
export RUST_LOG=warn
mvn compile exec:exec -Dnoria.log=DEBUG -Dnoria.examples.class=${1:-noria.examples.widgets.WidgetsKt}
